"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"

version = 3
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'
pwd = "osc7"

[palette]
mauve = "#cba6f7"
red = "#f38ba8"
blue = "#89b4fa"
lavender = "#b7bdf8"
subtext = "#6e738d"

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'path'
style = 'plain'
background = 'transparent'
foreground = 'p:lavender'
template = '{{ .Path }}'

[blocks.segments.properties]
style = 'full'

[[blocks.segments]]
type = 'git'
style = 'plain'
background = 'transparent'
foreground = 'p:subtext'
template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }}<p:blue>{{ if gt .Behind 0 }} ↓{{ end }}{{ if gt .Ahead 0 }} ↑{{ end }}</>'

[blocks.segments.properties]
branch_icon = ''
commit_icon = '@'
fetch_status = true

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
type = 'text'
style = 'plain'
background = 'transparent'
foreground = 'p:mauve'
foreground_templates = [
  '{{ if gt .Code 0 }}p:red{{ end }}',
  '{{ if eq .Code 0 }}p:mauve{{ end }}',
]
template = "❯"

[transient_prompt]
background = "transparent"
foreground = "p:mauve"
foreground_templates = [
  '{{if gt .Code 0}}p:red{{end}}',
  '{{if eq .Code 0}}p:mauve{{end}}',
]
template = "❯ "
